name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 0"

concurrency:
  group: tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - uses: actions/cache@v2
        with:
          path: ~/.cache/poetry
          key: poetry-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            poetry-

      - name: Install virtual-env
        run: |
          pip install -U pip
          pip install -U poetry
          poetry install

      - name: Run flake8
        run: poetry run flake8 manabi

      - name: Run mypy
        run: poetry run mypy manabi

      - name: Run isort
        run: poetry run isort --check-only manabi

      - name: Run black
        run: poetry run black --check manabi

  standard-tests:
    name: Run tests
    needs: [lint]
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install libsodium
        run: sudo apt-get install -y libsodium23

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.version }}

      - uses: actions/cache@v2
        with:
          path: ~/.cache/poetry
          key: poetry-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            poetry-

      - name: Install virtual-env
        run: |
          pip install -U pip
          pip install -U poetry
          poetry install

      - name: Run tests
        run: poetry run pytest manabi
