name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 0"

concurrency:
  group: tests-${{ github.ref }}
  cancel-in-progress: true

env:
  PYTHON_KEYRING_BACKEND: keyring.backends.null.Keyring

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - uses: actions/cache@v2
        with:
          path: ~/.venv
          key: poetry-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            poetry-

      - name: Install dependencies
        run: |
          pip install -U poetry
          poetry config virtualenvs.in-project true
          poetry install

      - name: Run flake8
        run: poetry run flake8 manabi

      - name: Run mypy
        run: poetry run mypy manabi

      - name: Run isort
        run: poetry run isort --check-only manabi

      - name: Run black
        run: poetry run black --check manabi

  compatibility-tests:
    name: Compatibility tests
    needs: [lint]
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"

    services:
      postgres:
        image: postgres:alpine
        env:
          POSTGRES_DB: manabi
          POSTGRES_USER: manabi
          POSTGRES_PASSWORD: manabi
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2

      - name: Setup environment
        run: sudo apt-get install -y libsodium23

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.version }}

      - uses: actions/cache@v2
        with:
          path: ~/.venv
          key: poetry-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            poetry-

      - name: Install dependendies
        run: |
          pip install -U poetry
          poetry config virtualenvs.in-project true
          poetry install

      - name: Run migrations
        run: poetry run python manabi_django/manage.py migrate manabi_migrations

      - name: Run tests
        run: poetry run pytest manabi
